tableau
.controller 'rightCtrl', ($scope, $mdDialog, $mdMedia) ->
  $scope.status = '  '
  $scope.customFullscreen = $mdMedia('xs') or $mdMedia('sm')

  

  $scope.showAlert = (ev) ->
    # Appending dialog to document.body to cover sidenav in docs app
    # Modal dialogs should fully cover application
    # to prevent interaction outside of dialog
    $mdDialog.show $mdDialog.alert().parent(angular.element(document.querySelector('#popupContainer'))).clickOutsideToClose(true).title('This is an alert title').textContent('You can specify some description text in here.').ariaLabel('Alert Dialog Demo').ok('Got it!').targetEvent(ev)
    return

  $scope.showConfirm = (ev) ->
    # Appending dialog to document.body to cover sidenav in docs app
    confirm = $mdDialog.confirm().title('Would you like to delete your debt?').textContent('All of the banks have agreed to forgive you your debts.').ariaLabel('Lucky day').targetEvent(ev).ok('Please do it!').cancel('Sounds like a scam')
    $mdDialog.show(confirm).then (->
      $scope.status = 'You decided to get rid of your debt.'
      return
    ), ->
      $scope.status = 'You decided to keep your debt.'
      return
    return

  $scope.showPrompt = (ev) ->
    # Appending dialog to document.body to cover sidenav in docs app
    confirm = $mdDialog.prompt().title('What would you name your dog?').textContent('Bowser is a common name.').placeholder('Dog name').ariaLabel('Dog name').initialValue('Buddy').targetEvent(ev).ok('Okay!').cancel('I\'m a cat person')
    $mdDialog.show(confirm).then ((result) ->
      $scope.status = 'You decided to name your dog ' + result + '.'
      return
    ), ->
      $scope.status = 'You didn\'t name your dog.'
      return
    return

  $scope.showAdvanced = (ev) ->
    useFullScreen = ($mdMedia('sm') or $mdMedia('xs')) and $scope.customFullscreen
    $mdDialog.show(
      controller: DialogController
      templateUrl: 'dialog1.tmpl.html'
      parent: angular.element(document.body)
      targetEvent: ev
      clickOutsideToClose: true
      fullscreen: useFullScreen).then ((answer) ->
      $scope.status = 'You said the information was "' + answer + '".'
      return
    ), ->
      $scope.status = 'You cancelled the dialog.'
      return
    $scope.$watch (->
      $mdMedia('xs') or $mdMedia('sm')
    ), (wantsFullScreen) ->
      $scope.customFullscreen = wantsFullScreen == true
      return
    return

  $scope.showTabDialog = (ev) ->
    $mdDialog.show(
      controller: DialogController
      templateUrl: 'tabDialog.tmpl.html'
      parent: angular.element(document.body)
      targetEvent: ev
      clickOutsideToClose: true).then ((answer) ->
      $scope.status = 'You said the information was "' + answer + '".'
      return
    ), ->
      $scope.status = 'You cancelled the dialog.'
      return
    return

  $scope.showPrerenderedDialog = (ev) ->
    $mdDialog.show
      controller: DialogController
      contentElement: '#myDialog'
      parent: angular.element(document.body)
      targetEvent: ev
      clickOutsideToClose: true
    return

  return

  DialogController = ($scope, $mdDialog) ->

    $scope.hide = ->
      $mdDialog.hide()
      return

    $scope.cancel = ->
      $mdDialog.cancel()
      return

    $scope.answer = (answer) ->
      $mdDialog.hide answer
      return

    return

###*
Copyright 2016 Google Inc. All Rights Reserved.
Use of this source code is governed by an MIT-style license that can be in foundin the LICENSE file at http://material.angularjs.org/license.
*
###

# ---
# generated by js2coffee 2.2.0
